XOS-97 make GuardDog multiple choice between npm and pypi (#28)

diff --git a/.github/workflows/test-git-crypt-unlock.yaml b/.github/workflows/test-git-crypt-unlock.yaml
--- a/.github/workflows/test-git-crypt-unlock.yaml
+++ b/.github/workflows/test-git-crypt-unlock.yaml
@@ -1,9 +1,9 @@
-name: 'Test git-crypt-unlock'
+name: "Test git-crypt-unlock"
 
 on:
     push:
-      branches:
-        - main
+        branches:
+            - main
 
 jobs:
     job:
@@ -16,7 +16,8 @@ jobs:
             - name: Git-crypt unlock
               uses: xip-online-applications/gha-workflow-templates/git-crypt-unlock@main
               with:
-                git-crypt-key: 'AEdJVENSWVBUS0VZAAAAAgAAAAAAAAABAAAABAAAAAAAAAADAAAAIISRqM2u8HMJg4Ev4IoJD9BG2qlfa6Pza8zhgZwipLOoAAAABQAAAEDZcLaTmNYQgiB+Hkjfr/lscNrNrl/fDQ2bDPPdHXLf7myTY3Xa1gujDGyrVKR8qQSl/r2JtOzyX6mx526BDkjTAAAAAA=='
+                  git-crypt-key: "AEdJVENSWVBUS0VZAAAAAgAAAAAAAAABAAAABAAAAAAAAAADAAAAIISRqM2u8HMJg4Ev4IoJD9BG2qlfa6Pza8zhgZwipLOoAAAABQAAAEDZcLaTmNYQgiB+Hkjfr/lscNrNrl/fDQ2bDPPdHXLf7myTY3Xa1gujDGyrVKR8qQSl/r2JtOzyX6mx526BDkjTAAAAAA=="
 
             - name: Test encrypted file
-              run: fgrep -xq "test file" ./git-crypt-unlock/test/test.txt || { echo "Test file could not be read"; exit 1; }
+              run: |
+                  fgrep -xq "test file" ./git-crypt-unlock/test/test.txt || { echo "Test file could not be read"; exit 1; }
