Added makefile for testing

diff --git a/.github/workflows/test-git-crypt-unlock.yaml b/.github/workflows/test-git-crypt-unlock.yaml
--- a/.github/workflows/test-git-crypt-unlock.yaml
+++ b/.github/workflows/test-git-crypt-unlock.yaml
@@ -19,4 +19,4 @@ jobs:
                 git-crypt-key: 'AEdJVENSWVBUS0VZAAAAAgAAAAAAAAABAAAABAAAAAAAAAADAAAAIISRqM2u8HMJg4Ev4IoJD9BG2qlfa6Pza8zhgZwipLOoAAAABQAAAEDZcLaTmNYQgiB+Hkjfr/lscNrNrl/fDQ2bDPPdHXLf7myTY3Xa1gujDGyrVKR8qQSl/r2JtOzyX6mx526BDkjTAAAAAA=='
 
             - name: Test encrypted file
-              run: cat ./git-crypt-unlock/test/test.txt
+              run: fgrep -xq "test file" ./git-crypt-unlock/test/test.txt || { echo "Test file could not be read"; exit 1; }
